// =============================================================================
// AI Token Price Compare — Data Layer
// All pricing in USD per 1M tokens unless otherwise noted
// Last updated: 2026-06-24
// =============================================================================

const PROVIDERS = {
  mimo: {
    id: 'mimo',
    name: 'MiMo',
    region: 'china',
    type: 'official',
    website: 'https://mimo.ai',
    color: '#8b5cf6',
  },
  // ─── GLOBAL OFFICIAL ──────────────────────────────────────────────────────────
  openai: {
    id: 'openai',
    name: 'OpenAI',
    region: 'global',
    type: 'official',
    website: 'https://openai.com',
    color: '#10a37f',
    description_en: 'Creator of GPT series, the most widely adopted AI models',
    description_id: 'Pembuat seri GPT, model AI yang paling banyak digunakan',
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic',
    region: 'global',
    type: 'official',
    website: 'https://anthropic.com',
    color: '#d4a27f',
    description_en: 'Creator of Claude, focused on AI safety and reliability',
    description_id: 'Pembuat Claude, berfokus pada keamanan dan keandalan AI',
  },
  google: {
    id: 'google',
    name: 'Google',
    region: 'global',
    type: 'official',
    website: 'https://ai.google.dev',
    color: '#4285f4',
    description_en: 'Creator of Gemini series with massive context windows',
    description_id: 'Pembuat seri Gemini dengan context window sangat besar',
  },
  mistral: {
    id: 'mistral',
    name: 'Mistral',
    region: 'global',
    type: 'official',
    website: 'https://mistral.ai',
    color: '#ff7000',
    description_en: 'European AI lab known for efficient open-weight models',
    description_id: 'Lab AI Eropa yang terkenal dengan model open-weight efisien',
  },
  meta: {
    id: 'meta',
    name: 'Meta',
    region: 'global',
    type: 'official',
    website: 'https://llama.meta.com',
    color: '#0668E1',
    description_en: 'Creator of the open-source Llama model family',
    description_id: 'Pembuat keluarga model open-source Llama',
  },
  deepseek: {
    id: 'deepseek',
    name: 'DeepSeek',
    region: 'global',
    type: 'official',
    website: 'https://deepseek.com',
    color: '#4d6bfe',
    description_en: 'Chinese AI lab offering high-quality models at very low prices',
    description_id: 'Lab AI Tiongkok yang menawarkan model berkualitas dengan harga sangat murah',
  },
  cohere: {
    id: 'cohere',
    name: 'Cohere',
    region: 'global',
    type: 'official',
    website: 'https://cohere.com',
    color: '#39594d',
    description_en: 'Enterprise-focused AI with strong RAG and search capabilities',
    description_id: 'AI untuk enterprise dengan kemampuan RAG dan pencarian yang kuat',
  },

  // ─── CHINA PROVIDERS ──────────────────────────────────────────────────────────
  alibaba: {
    id: 'alibaba',
    name: 'Alibaba / Qwen',
    region: 'china',
    type: 'official',
    website: 'https://www.alibabacloud.com/en/solutions/generative-ai/qwen',
    color: '#ff6a00',
    description_en: 'Alibaba Cloud\'s Qwen series — competitive and multilingual',
    description_id: 'Seri Qwen dari Alibaba Cloud — kompetitif dan multibahasa',
  },
  moonshot: {
    id: 'moonshot',
    name: 'Moonshot AI / Kimi',
    region: 'china',
    type: 'official',
    website: 'https://www.moonshot.cn',
    color: '#6366f1',
    description_en: 'Creator of Kimi, known for long-context capabilities',
    description_id: 'Pembuat Kimi, dikenal dengan kemampuan konteks panjang',
  },
  bytedance: {
    id: 'bytedance',
    name: 'ByteDance / Doubao',
    region: 'china',
    type: 'official',
    website: 'https://www.volcengine.com',
    color: '#325ab4',
    description_en: 'TikTok parent company\'s AI division with Doubao models',
    description_id: 'Divisi AI perusahaan induk TikTok dengan model Doubao',
  },
  zhipu: {
    id: 'zhipu',
    name: 'ZAI / GLM',
    region: 'china',
    type: 'official',
    website: 'https://z.ai',
    color: '#2563eb',
    description_en: 'ZAI, formerly Zhipu AI, creator of the GLM model family',
    description_id: 'ZAI, sebelumnya Zhipu AI, pembuat keluarga model GLM',
  },
  baidu: {
    id: 'baidu',
    name: 'Baidu / ERNIE',
    region: 'china',
    type: 'official',
    website: 'https://cloud.baidu.com',
    color: '#2932e1',
    description_en: 'China\'s search giant with ERNIE foundation models',
    description_id: 'Raksasa pencarian Tiongkok dengan model fondasi ERNIE',
  },
  yi: {
    id: 'yi',
    name: '01.AI / Yi',
    region: 'china',
    type: 'official',
    website: 'https://www.01.ai',
    color: '#00d4aa',
    description_en: 'Founded by Kai-Fu Lee, offering Yi bilingual models',
    description_id: 'Didirikan oleh Kai-Fu Lee, menawarkan model bilingual Yi',
  },
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    region: 'china',
    type: 'official',
    website: 'https://www.minimax.io',
    color: '#7c3aed',
    description_en: 'Known for million-token context and multimodal AI',
    description_id: 'Dikenal dengan konteks jutaan token dan AI multimodal',
  },
  stepfun: {
    id: 'stepfun',
    name: 'StepFun',
    region: 'china',
    type: 'official',
    website: 'https://www.stepfun.com',
    color: '#f97316',
    description_en: 'Chinese AI startup with Step series models',
    description_id: 'Startup AI Tiongkok dengan model seri Step',
  },
  xiaomi: {
    id: 'xiaomi',
    name: 'Xiaomi / MiMo',
    region: 'china',
    type: 'official',
    website: 'https://www.mi.com',
    color: '#ff6700',
    description_en: 'Xiaomi\'s open-source AI model for edge and mobile use',
    description_id: 'Model AI open-source Xiaomi untuk penggunaan edge dan mobile',
  },

  // ─── THIRD-PARTY PROVIDERS ────────────────────────────────────────────────────
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    region: 'global',
    type: 'third-party',
    website: 'https://openrouter.ai',
    color: '#8b5cf6',
    description_en: 'Unified API gateway to 200+ models from all major providers',
    description_id: 'Gateway API terpadu ke 200+ model dari semua penyedia utama',
  },
  sumopod: {
    id: 'sumopod',
    name: 'Sumopod',
    region: 'global',
    type: 'third-party',
    website: 'https://sumopod.com',
    color: '#f97316',
    description_en: 'Platform-as-a-Service offering AI API routes',
    description_id: 'Platform-as-a-Service yang menawarkan rute API AI',
  },
  deepinfra: {
    id: 'deepinfra',
    name: 'DeepInfra',
    region: 'global',
    type: 'third-party',
    website: 'https://deepinfra.com',
    color: '#7c3aed',
    description_en: 'High-performance AI inference platform hosting 100+ open-source models',
    description_id: 'Platform inferensi AI berkinerja tinggi yang menghosting 100+ model open-source',
  },
  xai: {
    id: 'xai',
    name: 'xAI',
    region: 'usa',
    type: 'official',
    website: 'https://x.ai',
    color: '#000000',
    description_en: 'Creators of Grok models',
    description_id: 'Pembuat model Grok',
  },
  minimax: {
    id: 'minimax',
    name: 'MiniMax',
    region: 'china',
    type: 'official',
    website: 'https://minimaxi.com',
    color: '#10b981',
    description_en: 'Leading Chinese AI lab',
    description_id: 'Laboratorium AI terkemuka Tiongkok',
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    region: 'global',
    type: 'third-party',
    website: 'https://console.groq.com',
    color: '#f55036',
    description_en: 'Ultra-fast LPU inference for open-source models. Free tier available.',
    description_id: 'Inferensi LPU ultra-cepat untuk model open-source. Ada tier gratis.',
  },
  cerebras: {
    id: 'cerebras',
    name: 'Cerebras',
    region: 'global',
    type: 'third-party',
    website: 'https://cloud.cerebras.ai',
    color: '#f97316',
    description_en: 'Wafer-scale AI chip inference. Extremely fast open-source model hosting.',
    description_id: 'Inferensi chip AI skala wafer. Hosting model open-source sangat cepat.',
  },
};

const MODELS = [
  {
    id: 'gpt-5-5-xhigh',
    name: 'GPT 5.5 (xHigh)',
    provider: 'openai',
    arenaRank: 1,
    inputPrice: 15,
    outputPrice: 60,
    cachePrice: 1.5,
    contextWindow: 200000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 15, cachePrice: 1.5, output: 60 },
      sumopod: { input: 15, cachePrice: 1.5, output: 60 },
      deepinfra: { input: 15, cachePrice: 1.5, output: 60 }
    },
  },
  {
    id: 'gpt-5-5-high',
    name: 'GPT 5.5 (High)',
    provider: 'openai',
    arenaRank: 2,
    inputPrice: 10,
    outputPrice: 30,
    cachePrice: 1,
    contextWindow: 200000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 10, cachePrice: 1, output: 30 },
      sumopod: { input: 10, cachePrice: 1, output: 30 },
      deepinfra: { input: 10, cachePrice: 1, output: 30 }
    },
  },
  {
    id: 'gpt-5-5',
    name: 'GPT 5.5',
    provider: 'openai',
    arenaRank: 3,
    inputPrice: 5,
    outputPrice: 15,
    cachePrice: 0.5,
    contextWindow: 200000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 5, cachePrice: 0.5, output: 15 },
      sumopod: { input: 5, cachePrice: 0.5, output: 15 },
      deepinfra: { input: 5, cachePrice: 0.5, output: 15 }
    },
  },
  {
    id: 'gpt-5-4-high',
    name: 'GPT 5.4 (High)',
    provider: 'openai',
    arenaRank: 4,
    inputPrice: 2.5,
    outputPrice: 10,
    cachePrice: 0.25,
    contextWindow: 128000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 2.5, cachePrice: 0.25, output: 10 },
      sumopod: { input: 2.5, cachePrice: 0.25, output: 10 },
      deepinfra: { input: 2.5, cachePrice: 0.25, output: 10 }
    },
  },
  {
    id: 'claude-fable-5',
    name: 'Claude Fable 5',
    provider: 'anthropic',
    arenaRank: 1,
    inputPrice: 12,
    outputPrice: 48,
    cachePrice: 1.2,
    contextWindow: 200000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 12, cachePrice: 1.2, output: 48 },
      sumopod: { input: 12, cachePrice: 1.2, output: 48 },
      deepinfra: { input: 12, cachePrice: 1.2, output: 48 }
    },
  },
  {
    id: 'claude-opus-4-8',
    name: 'Claude Opus 4.8 (Thinking)',
    provider: 'anthropic',
    arenaRank: 2,
    inputPrice: 15,
    outputPrice: 75,
    cachePrice: 1.5,
    contextWindow: 200000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'reasoning',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 15, cachePrice: 1.5, output: 75 },
      sumopod: { input: 15, cachePrice: 1.5, output: 75 },
      deepinfra: { input: 15, cachePrice: 1.5, output: 75 }
    },
  },
  {
    id: 'claude-opus-4-7',
    name: 'Claude Opus 4.7',
    provider: 'anthropic',
    arenaRank: 3,
    inputPrice: 8,
    outputPrice: 24,
    cachePrice: 0.8,
    contextWindow: 200000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 8, cachePrice: 0.8, output: 24 },
      sumopod: { input: 8, cachePrice: 0.8, output: 24 },
      deepinfra: { input: 8, cachePrice: 0.8, output: 24 }
    },
  },
  {
    id: 'claude-opus-4-6',
    name: 'Claude Opus 4.6',
    provider: 'anthropic',
    arenaRank: 4,
    inputPrice: 4,
    outputPrice: 12,
    cachePrice: 0.4,
    contextWindow: 200000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 4, cachePrice: 0.4, output: 12 },
      sumopod: { input: 4, cachePrice: 0.4, output: 12 },
      deepinfra: { input: 4, cachePrice: 0.4, output: 12 }
    },
  },
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    arenaRank: 4,
    inputPrice: 1.5,
    outputPrice: 4.5,
    cachePrice: 0.15,
    contextWindow: 200000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 1.5, cachePrice: 0.15, output: 4.5 },
      sumopod: { input: 1.5, cachePrice: 0.15, output: 4.5 },
      deepinfra: { input: 1.5, cachePrice: 0.15, output: 4.5 }
    },
  },
  {
    id: 'gemini-3-5-flash',
    name: 'Gemini 3.5 Flash',
    provider: 'google',
    arenaRank: 1,
    inputPrice: 0.1,
    outputPrice: 0.4,
    cachePrice: 0.01,
    contextWindow: 2000000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 0.1, cachePrice: 0.01, output: 0.4 },
      sumopod: { input: 0.1, cachePrice: 0.01, output: 0.4 },
      deepinfra: { input: 0.1, cachePrice: 0.01, output: 0.4 }
    },
  },
  {
    id: 'gemini-3-1-pro',
    name: 'Gemini 3.1 Pro Preview',
    provider: 'google',
    arenaRank: 2,
    inputPrice: 1.25,
    outputPrice: 5,
    cachePrice: 0.12,
    contextWindow: 2000000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 1.25, cachePrice: 0.12, output: 5 },
      sumopod: { input: 1.25, cachePrice: 0.12, output: 5 },
      deepinfra: { input: 1.25, cachePrice: 0.12, output: 5 }
    },
  },
  {
    id: 'gemini-3-flash',
    name: 'Gemini 3 Flash',
    provider: 'google',
    arenaRank: 3,
    inputPrice: 0.05,
    outputPrice: 0.2,
    cachePrice: 0.005,
    contextWindow: 2000000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 0.05, cachePrice: 0.005, output: 0.2 },
      sumopod: { input: 0.05, cachePrice: 0.005, output: 0.2 },
      deepinfra: { input: 0.05, cachePrice: 0.005, output: 0.2 }
    },
  },
  {
    id: 'grok-4-3-high',
    name: 'Grok 4.3 (High)',
    provider: 'xai',
    arenaRank: 1,
    inputPrice: 4,
    outputPrice: 12,
    cachePrice: 0.4,
    contextWindow: 128000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 4, cachePrice: 0.4, output: 12 },
      sumopod: { input: 4, cachePrice: 0.4, output: 12 },
      deepinfra: { input: 4, cachePrice: 0.4, output: 12 }
    },
  },
  {
    id: 'grok-4-3',
    name: 'Grok 4.3',
    provider: 'xai',
    arenaRank: 2,
    inputPrice: 2,
    outputPrice: 6,
    cachePrice: 0.2,
    contextWindow: 128000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 2, cachePrice: 0.2, output: 6 },
      sumopod: { input: 2, cachePrice: 0.2, output: 6 },
      deepinfra: { input: 2, cachePrice: 0.2, output: 6 }
    },
  },
  {
    id: 'grok-build-0-1',
    name: 'Grok Build 0.1',
    provider: 'xai',
    arenaRank: 3,
    inputPrice: 1,
    outputPrice: 3,
    cachePrice: 0.1,
    contextWindow: 128000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 1, cachePrice: 0.1, output: 3 },
      sumopod: { input: 1, cachePrice: 0.1, output: 3 },
      deepinfra: { input: 1, cachePrice: 0.1, output: 3 }
    },
  },
  {
    id: 'qwen-3-6-plus',
    name: 'Qwen 3.6 Plus',
    provider: 'alibaba',
    arenaRank: 1,
    inputPrice: 1,
    outputPrice: 3,
    cachePrice: 0.1,
    contextWindow: 128000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { input: 1, cachePrice: 0.1, output: 3 },
      sumopod: { input: 1, cachePrice: 0.1, output: 3 },
      deepinfra: { input: 1, cachePrice: 0.1, output: 3 }
    },
  },
  {
    id: 'minimax-m3',
    name: 'Minimax M3',
    provider: 'minimax',
    arenaRank: 1,
    inputPrice: 1,
    outputPrice: 3,
    cachePrice: 0.1,
    contextWindow: 128000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 1, cachePrice: 0.1, outputPrice: 3 },
      sumopod: { inputPrice: 1, cachePrice: 0.1, outputPrice: 3 },
      deepinfra: { inputPrice: 1, cachePrice: 0.1, outputPrice: 3 }
    },
  },

  // ─── KIMI / MOONSHOT TOP MODELS ──────────────────────────────────────────────
  {
    id: 'kimi-k2-7',
    name: 'Kimi K2.7',
    provider: 'moonshot',
    arenaRank: 1,
    inputPrice: 0.9,
    outputPrice: 3.4,
    cachePrice: 0.22,
    contextWindow: 256000,
    maxOutput: 32768,
    capabilities: ['reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    sourceUrl: 'https://platform.moonshot.ai/docs',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.9, cachePrice: 0.22, outputPrice: 3.4 },
      sumopod: { inputPrice: 0.93, cachePrice: 0.23, outputPrice: 3.48 },
      deepinfra: { inputPrice: 0.95, cachePrice: 0.24, outputPrice: 3.55 }
    },
  },
  {
    id: 'kimi-k2-6',
    name: 'Kimi K2.6',
    provider: 'moonshot',
    arenaRank: 2,
    inputPrice: 0.75,
    outputPrice: 2.9,
    cachePrice: 0.18,
    contextWindow: 256000,
    maxOutput: 32768,
    capabilities: ['reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-05-30',
    sourceUrl: 'https://platform.moonshot.ai/docs',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.75, cachePrice: 0.18, outputPrice: 2.9 },
      sumopod: { inputPrice: 0.78, cachePrice: 0.19, outputPrice: 2.98 },
      deepinfra: { inputPrice: 0.75, cachePrice: 0.15, outputPrice: 3.5, source: 'deepinfra-api', deepinfraId: 'moonshotai/Kimi-K2.6' }
    },
  },
  {
    id: 'kimi-k2',
    name: 'Kimi K2',
    provider: 'moonshot',
    arenaRank: 3,
    inputPrice: 0.6,
    outputPrice: 2.5,
    cachePrice: 0.15,
    contextWindow: 131000,
    maxOutput: 16384,
    capabilities: ['function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-04-18',
    sourceUrl: 'https://platform.moonshot.ai/docs',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.6, cachePrice: 0.15, outputPrice: 2.5 },
      sumopod: { inputPrice: 0.62, cachePrice: 0.16, outputPrice: 2.55 },
      deepinfra: { inputPrice: 0.75, cachePrice: 0.15, outputPrice: 3.5, source: 'deepinfra-api', deepinfraId: 'moonshotai/Kimi-K2.6' }
    },
  },
  {
    id: 'kimi-k2-thinking',
    name: 'Kimi K2 Thinking',
    provider: 'moonshot',
    arenaRank: 4,
    inputPrice: 0.8,
    outputPrice: 3,
    cachePrice: 0.2,
    contextWindow: 131000,
    maxOutput: 32768,
    capabilities: ['reasoning', 'function-calling', 'code'],
    category: 'reasoning',
    releaseDate: '2026-04-18',
    sourceUrl: 'https://platform.moonshot.ai/docs',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.8, cachePrice: 0.2, outputPrice: 3 },
      sumopod: { inputPrice: 0.82, cachePrice: 0.21, outputPrice: 3.1 },
      deepinfra: { inputPrice: 0.84, cachePrice: 0.21, outputPrice: 3.15 }
    },
  },
  {
    id: 'kimi-k1-5-long',
    name: 'Kimi K1.5 Long Context',
    provider: 'moonshot',
    arenaRank: 3,
    inputPrice: 0.35,
    outputPrice: 1.4,
    cachePrice: 0.08,
    contextWindow: 1000000,
    maxOutput: 16384,
    capabilities: ['json-mode', 'code'],
    category: 'mid',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.35, cachePrice: 0.08, outputPrice: 1.4 },
      sumopod: { inputPrice: 0.36, cachePrice: 0.09, outputPrice: 1.45 },
      deepinfra: { inputPrice: 0.38, cachePrice: 0.09, outputPrice: 1.5 }
    },
  },
  {
    id: 'kimi-latest-128k',
    name: 'Kimi Latest 128K',
    provider: 'moonshot',
    arenaRank: 4,
    inputPrice: 0.25,
    outputPrice: 1,
    cachePrice: 0.05,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.25, cachePrice: 0.05, outputPrice: 1 },
      sumopod: { inputPrice: 0.26, cachePrice: 0.06, outputPrice: 1.05 },
      deepinfra: { inputPrice: 0.27, cachePrice: 0.06, outputPrice: 1.08 }
    },
  },
  {
    id: 'kimi-latest-32k',
    name: 'Kimi Latest 32K',
    provider: 'moonshot',
    arenaRank: 5,
    inputPrice: 0.12,
    outputPrice: 0.5,
    cachePrice: 0.03,
    contextWindow: 32000,
    maxOutput: 8192,
    capabilities: ['json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.12, cachePrice: 0.03, outputPrice: 0.5 },
      sumopod: { inputPrice: 0.13, cachePrice: 0.03, outputPrice: 0.52 },
      deepinfra: { inputPrice: 0.14, cachePrice: 0.03, outputPrice: 0.55 }
    },
  },

  // ─── XIAOMI MIMO TOP MODELS ──────────────────────────────────────────────────
  {
    id: 'mimo-v2-5-pro',
    name: 'MiMo-V2.5-Pro',
    provider: 'xiaomi',
    arenaRank: 1,
    inputPrice: 0.2,
    outputPrice: 0.8,
    cachePrice: 0.05,
    contextWindow: 256000,
    maxOutput: 32768,
    capabilities: ['reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    sourceUrl: 'https://github.com/XiaomiMiMo/MiMo',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.2, cachePrice: 0.05, outputPrice: 0.8, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.22, cachePrice: 0.055, outputPrice: 0.85, source: 'router-curated' },
      deepinfra: { inputPrice: 0.22, cachePrice: 0.055, outputPrice: 0.88, source: 'router-curated' }
    },
  },
  {
    id: 'mimo-vl-7b',
    name: 'MiMo-VL-7B',
    provider: 'xiaomi',
    arenaRank: 2,
    inputPrice: 0.08,
    outputPrice: 0.24,
    cachePrice: 0.02,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['vision', 'json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.08, cachePrice: 0.02, outputPrice: 0.24 },
      sumopod: { inputPrice: 0.09, cachePrice: 0.02, outputPrice: 0.26 },
      deepinfra: { inputPrice: 0.09, cachePrice: 0.02, outputPrice: 0.27 }
    },
  },
  {
    id: 'mimo-7b-rl',
    name: 'MiMo-7B-RL',
    provider: 'xiaomi',
    arenaRank: 3,
    inputPrice: 0.06,
    outputPrice: 0.18,
    cachePrice: 0.015,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['reasoning', 'code'],
    category: 'reasoning',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.06, cachePrice: 0.015, outputPrice: 0.18 },
      sumopod: { inputPrice: 0.07, cachePrice: 0.016, outputPrice: 0.2 },
      deepinfra: { inputPrice: 0.07, cachePrice: 0.016, outputPrice: 0.21 }
    },
  },
  {
    id: 'mimo-7b-base',
    name: 'MiMo-7B Base',
    provider: 'xiaomi',
    arenaRank: 3,
    inputPrice: 0.04,
    outputPrice: 0.12,
    cachePrice: 0.01,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.04, cachePrice: 0.01, outputPrice: 0.12 },
      sumopod: { inputPrice: 0.05, cachePrice: 0.01, outputPrice: 0.14 },
      deepinfra: { inputPrice: 0.05, cachePrice: 0.01, outputPrice: 0.15 }
    },
  },
  {
    id: 'mimo-7b-sft',
    name: 'MiMo-7B-SFT',
    provider: 'xiaomi',
    arenaRank: 4,
    inputPrice: 0.05,
    outputPrice: 0.15,
    cachePrice: 0.01,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['json-mode', 'code'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.05, cachePrice: 0.01, outputPrice: 0.15 },
      sumopod: { inputPrice: 0.055, cachePrice: 0.012, outputPrice: 0.16 },
      deepinfra: { inputPrice: 0.06, cachePrice: 0.012, outputPrice: 0.17 }
    },
  },
  {
    id: 'mimo-lite',
    name: 'MiMo Lite',
    provider: 'xiaomi',
    arenaRank: 5,
    inputPrice: 0.02,
    outputPrice: 0.08,
    cachePrice: 0.005,
    contextWindow: 32000,
    maxOutput: 4096,
    capabilities: ['json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.02, cachePrice: 0.005, outputPrice: 0.08 },
      sumopod: { inputPrice: 0.025, cachePrice: 0.006, outputPrice: 0.09 },
      deepinfra: { inputPrice: 0.03, cachePrice: 0.006, outputPrice: 0.1 }
    },
  },

  // ─── ZAI / GLM TOP MODELS ────────────────────────────────────────────────────
  {
    id: 'glm-5-2',
    name: 'GLM-5.2',
    provider: 'zhipu',
    arenaRank: 1,
    inputPrice: 0.9,
    outputPrice: 3.6,
    cachePrice: 0.18,
    contextWindow: 256000,
    maxOutput: 32768,
    capabilities: ['reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    sourceUrl: 'https://docs.z.ai',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.9, cachePrice: 0.18, outputPrice: 3.6 },
      sumopod: { inputPrice: 0.93, cachePrice: 0.19, outputPrice: 3.72 },
      deepinfra: { inputPrice: 0.95, cachePrice: 0.2, outputPrice: 3.8 }
    },
  },
  {
    id: 'glm-5-2-air',
    name: 'GLM-5.2-Air',
    provider: 'zhipu',
    arenaRank: 2,
    inputPrice: 0.18,
    outputPrice: 0.72,
    cachePrice: 0.04,
    contextWindow: 256000,
    maxOutput: 32768,
    capabilities: ['reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'reasoning',
    releaseDate: '2026-06-24',
    sourceUrl: 'https://docs.z.ai',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.18, cachePrice: 0.04, outputPrice: 0.72 },
      sumopod: { inputPrice: 0.19, cachePrice: 0.042, outputPrice: 0.75 },
      deepinfra: { inputPrice: 0.2, cachePrice: 0.045, outputPrice: 0.78 }
    },
  },
  {
    id: 'glm-4-5',
    name: 'GLM-4.5',
    provider: 'zhipu',
    arenaRank: 3,
    inputPrice: 0.6,
    outputPrice: 2.2,
    cachePrice: 0.12,
    contextWindow: 128000,
    maxOutput: 16384,
    capabilities: ['reasoning', 'function-calling', 'code'],
    category: 'flagship',
    releaseDate: '2026-04-20',
    sourceUrl: 'https://docs.z.ai',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.6, cachePrice: 0.12, outputPrice: 2.2 },
      sumopod: { inputPrice: 0.62, cachePrice: 0.13, outputPrice: 2.25 },
      deepinfra: { inputPrice: 0.6, cachePrice: 0.12, outputPrice: 2.08, source: 'deepinfra-api', deepinfraId: 'zai-org/GLM-5' }
    },
  },
  {
    id: 'glm-4-plus',
    name: 'GLM-4-Plus',
    provider: 'zhipu',
    arenaRank: 2,
    inputPrice: 0.35,
    outputPrice: 1.4,
    cachePrice: 0.08,
    contextWindow: 128000,
    maxOutput: 16384,
    capabilities: ['function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.35, cachePrice: 0.08, outputPrice: 1.4 },
      sumopod: { inputPrice: 0.36, cachePrice: 0.09, outputPrice: 1.45 },
      deepinfra: { inputPrice: 0.43, cachePrice: 0.08, outputPrice: 1.74, source: 'deepinfra-api', deepinfraId: 'zai-org/GLM-4.6' }
    },
  },
  {
    id: 'glm-4-air',
    name: 'GLM-4-Air',
    provider: 'zhipu',
    arenaRank: 3,
    inputPrice: 0.08,
    outputPrice: 0.24,
    cachePrice: 0.02,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.08, cachePrice: 0.02, outputPrice: 0.24 },
      sumopod: { inputPrice: 0.09, cachePrice: 0.02, outputPrice: 0.26 },
      deepinfra: { inputPrice: 0.09, cachePrice: 0.02, outputPrice: 0.27 }
    },
  },
  {
    id: 'glm-4-flash',
    name: 'GLM-4-Flash',
    provider: 'zhipu',
    arenaRank: 4,
    inputPrice: 0.01,
    outputPrice: 0.01,
    cachePrice: 0.002,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.01, cachePrice: 0.002, outputPrice: 0.01 },
      sumopod: { inputPrice: 0.012, cachePrice: 0.002, outputPrice: 0.012 },
      deepinfra: { inputPrice: 0.012, cachePrice: 0.002, outputPrice: 0.012 }
    },
  },
  {
    id: 'glm-z1-air',
    name: 'GLM-Z1-Air',
    provider: 'zhipu',
    arenaRank: 5,
    inputPrice: 0.1,
    outputPrice: 0.3,
    cachePrice: 0.025,
    contextWindow: 128000,
    maxOutput: 16384,
    capabilities: ['reasoning', 'code'],
    category: 'reasoning',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.1, cachePrice: 0.025, outputPrice: 0.3 },
      sumopod: { inputPrice: 0.11, cachePrice: 0.026, outputPrice: 0.32 },
      deepinfra: { inputPrice: 0.11, cachePrice: 0.026, outputPrice: 0.33 }
    },
  },

  // ─── DEEPSEEK TOP MODELS ─────────────────────────────────────────────────────
  {
    id: 'deepseek-v3-1',
    name: 'DeepSeek V3.1',
    provider: 'deepseek',
    arenaRank: 1,
    inputPrice: 0.27,
    outputPrice: 1.1,
    cachePrice: 0.07,
    contextWindow: 128000,
    maxOutput: 16384,
    capabilities: ['function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.27, cachePrice: 0.07, outputPrice: 1.1 },
      sumopod: { inputPrice: 0.28, cachePrice: 0.07, outputPrice: 1.15 },
      deepinfra: { inputPrice: 0.29, cachePrice: 0.08, outputPrice: 1.18 }
    },
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'deepseek',
    arenaRank: 2,
    inputPrice: 0.55,
    outputPrice: 2.19,
    cachePrice: 0.14,
    contextWindow: 128000,
    maxOutput: 32768,
    capabilities: ['reasoning', 'code'],
    category: 'reasoning',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.55, cachePrice: 0.14, outputPrice: 2.19 },
      sumopod: { inputPrice: 0.57, cachePrice: 0.15, outputPrice: 2.25 },
      deepinfra: { inputPrice: 0.5, cachePrice: 0.35, outputPrice: 2.15, source: 'deepinfra-api', deepinfraId: 'deepseek-ai/DeepSeek-R1-0528' }
    },
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'deepseek',
    arenaRank: 3,
    inputPrice: 0.27,
    outputPrice: 1.1,
    cachePrice: 0.07,
    contextWindow: 64000,
    maxOutput: 8192,
    capabilities: ['json-mode', 'code'],
    category: 'mid',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.27, cachePrice: 0.07, outputPrice: 1.1 },
      sumopod: { inputPrice: 0.28, cachePrice: 0.07, outputPrice: 1.15 },
      deepinfra: { inputPrice: 0.26, cachePrice: 0.13, outputPrice: 0.38, source: 'deepinfra-api', deepinfraId: 'deepseek-ai/DeepSeek-V3.2' }
    },
  },
  {
    id: 'deepseek-chat',
    name: 'DeepSeek Chat',
    provider: 'deepseek',
    arenaRank: 4,
    inputPrice: 0.14,
    outputPrice: 0.28,
    cachePrice: 0.014,
    contextWindow: 64000,
    maxOutput: 8192,
    capabilities: ['json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.14, cachePrice: 0.014, outputPrice: 0.28 },
      sumopod: { inputPrice: 0.15, cachePrice: 0.015, outputPrice: 0.3 },
      deepinfra: { inputPrice: 0.15, cachePrice: 0.015, outputPrice: 0.32 }
    },
  },
  {
    id: 'deepseek-coder-v2',
    name: 'DeepSeek Coder V2',
    provider: 'deepseek',
    arenaRank: 5,
    inputPrice: 0.14,
    outputPrice: 0.28,
    cachePrice: 0.014,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['code', 'json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.14, cachePrice: 0.014, outputPrice: 0.28 },
      sumopod: { inputPrice: 0.15, cachePrice: 0.015, outputPrice: 0.3 },
      deepinfra: { inputPrice: 0.15, cachePrice: 0.015, outputPrice: 0.32 }
    },
  },
];

const DEFAULT_DATA_UPDATED_AT = '2026-07-01';

const DEPRECATED_CURATED_MODEL_IDS = new Set([
  'grok-4-3-high',
  'grok-build-0-1',
  'kimi-latest-128k',
  'kimi-latest-32k',
  'glm-z1-air',
  'command-light',
  'abab6-5s-chat',
]);

const CURATED_TOP_MODELS = [
  // OpenAI official docs, fetched 2026-06-24.
  {
    id: 'gpt-5-5-official',
    name: 'GPT-5.5',
    provider: 'openai',
    arenaRank: 1,
    inputPrice: 5,
    outputPrice: 30,
    cachePrice: 0.5,
    contextWindow: 1000000,
    maxOutput: 128000,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://platform.openai.com/docs/models',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 5, cachePrice: 0.5, outputPrice: 30, source: 'aggregator-curated' },
      sumopod: { inputPrice: 5.1, cachePrice: 0.52, outputPrice: 30.6, source: 'router-curated' },
      deepinfra: { inputPrice: 5.2, cachePrice: 0.52, outputPrice: 31, source: 'router-curated' }
    },
  },
  {
    id: 'gpt-5-4-official',
    name: 'GPT-5.4',
    provider: 'openai',
    arenaRank: 2,
    inputPrice: 2.5,
    outputPrice: 15,
    cachePrice: 0.25,
    contextWindow: 1000000,
    maxOutput: 128000,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://platform.openai.com/docs/models',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 2.5, cachePrice: 0.25, outputPrice: 15, source: 'aggregator-curated' },
      sumopod: { inputPrice: 2.55, cachePrice: 0.26, outputPrice: 15.3, source: 'router-curated' },
      deepinfra: { inputPrice: 2.6, cachePrice: 0.26, outputPrice: 15.5, source: 'router-curated' }
    },
  },
  {
    id: 'gpt-5-4-mini',
    name: 'GPT-5.4 Mini',
    provider: 'openai',
    arenaRank: 3,
    inputPrice: 0.75,
    outputPrice: 4.5,
    cachePrice: 0.075,
    contextWindow: 400000,
    maxOutput: 128000,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'mid',
    releaseDate: '2026-06-24',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://platform.openai.com/docs/models',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.75, cachePrice: 0.075, outputPrice: 4.5, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.78, cachePrice: 0.08, outputPrice: 4.65, source: 'router-curated' },
      deepinfra: { inputPrice: 0.8, cachePrice: 0.08, outputPrice: 4.7, source: 'router-curated' }
    },
  },
  {
    id: 'gpt-5-4-nano',
    name: 'GPT-5.4 Nano',
    provider: 'openai',
    arenaRank: 4,
    inputPrice: 0.15,
    outputPrice: 0.6,
    cachePrice: 0.015,
    contextWindow: 128000,
    maxOutput: 32768,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://platform.openai.com/docs/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.15, cachePrice: 0.015, outputPrice: 0.6, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.16, cachePrice: 0.016, outputPrice: 0.62, source: 'router-curated' },
      deepinfra: { inputPrice: 0.16, cachePrice: 0.016, outputPrice: 0.64, source: 'router-curated' }
    },
  },

  // Anthropic official docs, fetched 2026-06-24.
  {
    id: 'claude-mythos-5',
    name: 'Claude Mythos 5',
    provider: 'anthropic',
    arenaRank: 1,
    inputPrice: 10,
    outputPrice: 50,
    cachePrice: 1,
    contextWindow: 1000000,
    maxOutput: 128000,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-06-09',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/models',
    confidence: 'medium',
    status: 'limited',
    thirdPartyPricing: {
      openrouter: { inputPrice: 10, cachePrice: 1, outputPrice: 50, source: 'aggregator-curated' }
    },
  },
  {
    id: 'claude-opus-4-8-fast',
    name: 'Claude Opus 4.8 Fast',
    provider: 'anthropic',
    arenaRank: 3,
    inputPrice: 5,
    outputPrice: 25,
    cachePrice: 0.5,
    contextWindow: 1000000,
    maxOutput: 128000,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 5, cachePrice: 0.5, outputPrice: 25, source: 'aggregator-curated' }
    },
  },
  {
    id: 'claude-sonnet-4-5',
    name: 'Claude Sonnet 4.5',
    provider: 'anthropic',
    arenaRank: 6,
    inputPrice: 3,
    outputPrice: 15,
    cachePrice: 0.3,
    contextWindow: 200000,
    maxOutput: 64000,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2025-09-29',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 3, cachePrice: 0.3, outputPrice: 15, source: 'aggregator-curated' }
    },
  },
  {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    provider: 'anthropic',
    arenaRank: 7,
    inputPrice: 1,
    outputPrice: 5,
    cachePrice: 0.1,
    contextWindow: 200000,
    maxOutput: 64000,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2025-10-01',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.anthropic.com/en/docs/about-claude/models',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 1, cachePrice: 0.1, outputPrice: 5, source: 'aggregator-curated' },
      sumopod: { inputPrice: 1.03, cachePrice: 0.1, outputPrice: 5.15, source: 'router-curated' },
      deepinfra: { inputPrice: 1.05, cachePrice: 0.11, outputPrice: 5.25, source: 'router-curated' }
    },
  },

  // Google Gemini curated official catalog.
  {
    id: 'gemini-2-5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    arenaRank: 1,
    inputPrice: 1.25,
    outputPrice: 10,
    cachePrice: 0.31,
    contextWindow: 2000000,
    maxOutput: 65536,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2025-06-17',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/models',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 1.25, cachePrice: 0.31, outputPrice: 10, source: 'aggregator-curated' },
      sumopod: { inputPrice: 1.3, cachePrice: 0.32, outputPrice: 10.3, source: 'router-curated' },
      deepinfra: { inputPrice: 1.35, cachePrice: 0.33, outputPrice: 10.5, source: 'router-curated' }
    },
  },
  {
    id: 'gemini-2-5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google',
    arenaRank: 2,
    inputPrice: 0.3,
    outputPrice: 2.5,
    cachePrice: 0.075,
    contextWindow: 1000000,
    maxOutput: 65536,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'mid',
    releaseDate: '2025-06-17',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/models',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.3, cachePrice: 0.075, outputPrice: 2.5, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.31, cachePrice: 0.08, outputPrice: 2.6, source: 'router-curated' },
      deepinfra: { inputPrice: 0.3, outputPrice: 2.5, source: 'deepinfra-api', deepinfraId: 'google/gemini-2.5-flash' }
    },
  },
  {
    id: 'gemini-2-5-flash-lite',
    name: 'Gemini 2.5 Flash-Lite',
    provider: 'google',
    arenaRank: 3,
    inputPrice: 0.1,
    outputPrice: 0.4,
    cachePrice: 0.025,
    contextWindow: 1000000,
    maxOutput: 65536,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'budget',
    releaseDate: '2025-06-17',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/models',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.1, cachePrice: 0.025, outputPrice: 0.4, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.11, cachePrice: 0.026, outputPrice: 0.42, source: 'router-curated' },
      deepinfra: { inputPrice: 0.11, cachePrice: 0.026, outputPrice: 0.43, source: 'router-curated' }
    },
  },
  {
    id: 'gemini-2-0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'google',
    arenaRank: 4,
    inputPrice: 0.1,
    outputPrice: 0.4,
    cachePrice: 0.025,
    contextWindow: 1000000,
    maxOutput: 8192,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'budget',
    releaseDate: '2025-02-05',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/models',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.1, cachePrice: 0.025, outputPrice: 0.4, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.11, cachePrice: 0.026, outputPrice: 0.42, source: 'router-curated' },
      deepinfra: { inputPrice: 0.11, cachePrice: 0.026, outputPrice: 0.43, source: 'router-curated' }
    },
  },
  {
    id: 'gemini-1-5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'google',
    arenaRank: 5,
    inputPrice: 1.25,
    outputPrice: 5,
    cachePrice: 0.31,
    contextWindow: 2000000,
    maxOutput: 8192,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2024-05-14',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://ai.google.dev/gemini-api/docs/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 1.25, cachePrice: 0.31, outputPrice: 5, source: 'aggregator-curated' },
      sumopod: { inputPrice: 1.3, cachePrice: 0.32, outputPrice: 5.2, source: 'router-curated' },
      deepinfra: { inputPrice: 1.35, cachePrice: 0.33, outputPrice: 5.25, source: 'router-curated' }
    },
  },

  // xAI official catalog.
  {
    id: 'grok-4',
    name: 'Grok 4',
    provider: 'xai',
    arenaRank: 1,
    inputPrice: 3,
    outputPrice: 15,
    cachePrice: 0.75,
    contextWindow: 256000,
    maxOutput: 16384,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2025-07-09',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.x.ai/docs/models',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 3, cachePrice: 0.75, outputPrice: 15, source: 'aggregator-curated' },
      sumopod: { inputPrice: 3.1, cachePrice: 0.78, outputPrice: 15.5, source: 'router-curated' },
      deepinfra: { inputPrice: 3.15, cachePrice: 0.8, outputPrice: 15.75, source: 'router-curated' }
    },
  },
  {
    id: 'grok-3',
    name: 'Grok 3',
    provider: 'xai',
    arenaRank: 2,
    inputPrice: 3,
    outputPrice: 15,
    cachePrice: 0.75,
    contextWindow: 131000,
    maxOutput: 8192,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode'],
    category: 'flagship',
    releaseDate: '2025-02-17',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.x.ai/docs/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 3, cachePrice: 0.75, outputPrice: 15, source: 'aggregator-curated' },
      sumopod: { inputPrice: 3.1, cachePrice: 0.78, outputPrice: 15.5, source: 'router-curated' },
      deepinfra: { inputPrice: 3.15, cachePrice: 0.8, outputPrice: 15.75, source: 'router-curated' }
    },
  },
  {
    id: 'grok-3-mini',
    name: 'Grok 3 Mini',
    provider: 'xai',
    arenaRank: 3,
    inputPrice: 0.3,
    outputPrice: 0.5,
    cachePrice: 0.075,
    contextWindow: 131000,
    maxOutput: 8192,
    capabilities: ['reasoning', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2025-02-17',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.x.ai/docs/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.3, cachePrice: 0.075, outputPrice: 0.5, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.31, cachePrice: 0.08, outputPrice: 0.52, source: 'router-curated' },
      deepinfra: { inputPrice: 0.32, cachePrice: 0.08, outputPrice: 0.54, source: 'router-curated' }
    },
  },
  {
    id: 'grok-code-fast-1',
    name: 'Grok Code Fast 1',
    provider: 'xai',
    arenaRank: 4,
    inputPrice: 0.2,
    outputPrice: 1.5,
    cachePrice: 0.02,
    contextWindow: 256000,
    maxOutput: 16384,
    capabilities: ['code', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2025-08-28',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.x.ai/docs/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.2, cachePrice: 0.02, outputPrice: 1.5, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.21, cachePrice: 0.022, outputPrice: 1.55, source: 'router-curated' },
      deepinfra: { inputPrice: 0.22, cachePrice: 0.022, outputPrice: 1.6, source: 'router-curated' }
    },
  },
  {
    id: 'grok-2-vision',
    name: 'Grok 2 Vision',
    provider: 'xai',
    arenaRank: 5,
    inputPrice: 2,
    outputPrice: 10,
    cachePrice: 0.5,
    contextWindow: 32768,
    maxOutput: 8192,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2024-08-13',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.x.ai/docs/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 2, cachePrice: 0.5, outputPrice: 10, source: 'aggregator-curated' },
      sumopod: { inputPrice: 2.1, cachePrice: 0.52, outputPrice: 10.4, source: 'router-curated' },
      deepinfra: { inputPrice: 2.15, cachePrice: 0.54, outputPrice: 10.5, source: 'router-curated' }
    },
  },

  // Alibaba Qwen / DashScope.
  {
    id: 'qwen3-max',
    name: 'Qwen3-Max',
    provider: 'alibaba',
    arenaRank: 1,
    inputPrice: 1.6,
    outputPrice: 6.4,
    cachePrice: 0.4,
    contextWindow: 1000000,
    maxOutput: 32768,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://www.alibabacloud.com/help/en/model-studio/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 1.6, cachePrice: 0.4, outputPrice: 6.4, source: 'aggregator-curated' },
      sumopod: { inputPrice: 1.65, cachePrice: 0.42, outputPrice: 6.6, source: 'router-curated' },
      deepinfra: { inputPrice: 1.7, cachePrice: 0.42, outputPrice: 6.8, source: 'router-curated' }
    },
  },
  {
    id: 'qwen3-plus',
    name: 'Qwen3-Plus',
    provider: 'alibaba',
    arenaRank: 2,
    inputPrice: 0.8,
    outputPrice: 2.4,
    cachePrice: 0.2,
    contextWindow: 1000000,
    maxOutput: 32768,
    capabilities: ['reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'mid',
    releaseDate: '2026-06-24',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://www.alibabacloud.com/help/en/model-studio/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.8, cachePrice: 0.2, outputPrice: 2.4, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.84, cachePrice: 0.21, outputPrice: 2.5, source: 'router-curated' },
      deepinfra: { inputPrice: 0.86, cachePrice: 0.22, outputPrice: 2.55, source: 'router-curated' }
    },
  },
  {
    id: 'qwen3-235b-a22b',
    name: 'Qwen3-235B-A22B',
    provider: 'alibaba',
    arenaRank: 3,
    inputPrice: 0.22,
    outputPrice: 0.88,
    cachePrice: 0.055,
    contextWindow: 262000,
    maxOutput: 32768,
    capabilities: ['reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'reasoning',
    releaseDate: '2025-04-29',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://qwenlm.github.io',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.22, cachePrice: 0.055, outputPrice: 0.88, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.24, cachePrice: 0.06, outputPrice: 0.95, source: 'router-curated' },
      deepinfra: { inputPrice: 0.09, outputPrice: 0.1, source: 'deepinfra-api', deepinfraId: 'Qwen/Qwen3-235B-A22B-Instruct-2507' }
    },
  },
  {
    id: 'qwen3-coder-plus',
    name: 'Qwen3-Coder-Plus',
    provider: 'alibaba',
    arenaRank: 4,
    inputPrice: 1,
    outputPrice: 5,
    cachePrice: 0.25,
    contextWindow: 256000,
    maxOutput: 32768,
    capabilities: ['code', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2026-06-24',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://www.alibabacloud.com/help/en/model-studio/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 1, cachePrice: 0.25, outputPrice: 5, source: 'aggregator-curated' },
      sumopod: { inputPrice: 1.05, cachePrice: 0.26, outputPrice: 5.2, source: 'router-curated' },
      deepinfra: { inputPrice: 1.08, cachePrice: 0.27, outputPrice: 5.25, source: 'router-curated' }
    },
  },
  {
    id: 'qwen3-turbo',
    name: 'Qwen3-Turbo',
    provider: 'alibaba',
    arenaRank: 5,
    inputPrice: 0.05,
    outputPrice: 0.2,
    cachePrice: 0.012,
    contextWindow: 1000000,
    maxOutput: 32768,
    capabilities: ['function-calling', 'json-mode'],
    category: 'budget',
    releaseDate: '2026-06-24',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://www.alibabacloud.com/help/en/model-studio/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.05, cachePrice: 0.012, outputPrice: 0.2, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.055, cachePrice: 0.013, outputPrice: 0.22, source: 'router-curated' },
      deepinfra: { inputPrice: 0.06, cachePrice: 0.014, outputPrice: 0.24, source: 'router-curated' }
    },
  },

  // Mistral AI.
  {
    id: 'mistral-large-latest',
    name: 'Mistral Large',
    provider: 'mistral',
    arenaRank: 1,
    inputPrice: 2,
    outputPrice: 6,
    cachePrice: 0.2,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2025-11-18',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.mistral.ai/getting-started/models/',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 2, cachePrice: 0.2, outputPrice: 6, source: 'aggregator-curated' },
      sumopod: { inputPrice: 2.1, cachePrice: 0.21, outputPrice: 6.2, source: 'router-curated' },
      deepinfra: { inputPrice: 2.15, cachePrice: 0.22, outputPrice: 6.3, source: 'router-curated' }
    },
  },
  {
    id: 'magistral-medium-latest',
    name: 'Magistral Medium',
    provider: 'mistral',
    arenaRank: 2,
    inputPrice: 2,
    outputPrice: 5,
    cachePrice: 0.2,
    contextWindow: 40000,
    maxOutput: 8192,
    capabilities: ['reasoning', 'code', 'json-mode'],
    category: 'reasoning',
    releaseDate: '2025-06-10',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.mistral.ai/getting-started/models/',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 2, cachePrice: 0.2, outputPrice: 5, source: 'aggregator-curated' },
      sumopod: { inputPrice: 2.1, cachePrice: 0.21, outputPrice: 5.2, source: 'router-curated' },
      deepinfra: { inputPrice: 2.15, cachePrice: 0.22, outputPrice: 5.25, source: 'router-curated' }
    },
  },
  {
    id: 'codestral-latest',
    name: 'Codestral',
    provider: 'mistral',
    arenaRank: 3,
    inputPrice: 0.2,
    outputPrice: 0.6,
    cachePrice: 0.02,
    contextWindow: 256000,
    maxOutput: 8192,
    capabilities: ['code', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2025-01-13',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.mistral.ai/getting-started/models/',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.2, cachePrice: 0.02, outputPrice: 0.6, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.22, cachePrice: 0.022, outputPrice: 0.65, source: 'router-curated' },
      deepinfra: { inputPrice: 0.22, cachePrice: 0.022, outputPrice: 0.66, source: 'router-curated' }
    },
  },
  {
    id: 'mistral-small-latest',
    name: 'Mistral Small',
    provider: 'mistral',
    arenaRank: 4,
    inputPrice: 0.1,
    outputPrice: 0.3,
    cachePrice: 0.01,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['function-calling', 'json-mode'],
    category: 'budget',
    releaseDate: '2025-03-17',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.mistral.ai/getting-started/models/',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.1, cachePrice: 0.01, outputPrice: 0.3, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.11, cachePrice: 0.011, outputPrice: 0.32, source: 'router-curated' },
      deepinfra: { inputPrice: 0.11, cachePrice: 0.011, outputPrice: 0.33, source: 'router-curated' }
    },
  },
  {
    id: 'ministral-8b-latest',
    name: 'Ministral 8B',
    provider: 'mistral',
    arenaRank: 5,
    inputPrice: 0.1,
    outputPrice: 0.1,
    cachePrice: 0.01,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['json-mode'],
    category: 'budget',
    releaseDate: '2024-10-16',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.mistral.ai/getting-started/models/',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.1, cachePrice: 0.01, outputPrice: 0.1, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.11, cachePrice: 0.011, outputPrice: 0.12, source: 'router-curated' },
      deepinfra: { inputPrice: 0.11, cachePrice: 0.011, outputPrice: 0.13, source: 'router-curated' }
    },
  },

  // Meta Llama open-weight ecosystem.
  {
    id: 'llama-4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'meta',
    arenaRank: 1,
    inputPrice: 0.2,
    outputPrice: 0.6,
    cachePrice: 0.02,
    contextWindow: 1000000,
    maxOutput: 16384,
    capabilities: ['vision', 'reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2025-04-05',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://llama.meta.com',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.2, cachePrice: 0.02, outputPrice: 0.6, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.22, cachePrice: 0.022, outputPrice: 0.65, source: 'router-curated' },
      deepinfra: { inputPrice: 0.22, cachePrice: 0.022, outputPrice: 0.66, source: 'router-curated' }
    },
  },
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout',
    provider: 'meta',
    arenaRank: 2,
    inputPrice: 0.1,
    outputPrice: 0.3,
    cachePrice: 0.01,
    contextWindow: 10000000,
    maxOutput: 16384,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2025-04-05',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://llama.meta.com',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.1, cachePrice: 0.01, outputPrice: 0.3, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.11, cachePrice: 0.011, outputPrice: 0.32, source: 'router-curated' },
      deepinfra: { inputPrice: 0.11, cachePrice: 0.011, outputPrice: 0.33, source: 'router-curated' }
    },
  },
  {
    id: 'llama-3-3-70b-instruct',
    name: 'Llama 3.3 70B Instruct',
    provider: 'meta',
    arenaRank: 3,
    inputPrice: 0.07,
    outputPrice: 0.25,
    cachePrice: 0.01,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['function-calling', 'json-mode', 'code'],
    category: 'budget',
    releaseDate: '2024-12-06',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://llama.meta.com',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.07, cachePrice: 0.01, outputPrice: 0.25, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.08, cachePrice: 0.01, outputPrice: 0.28, source: 'router-curated' },
      deepinfra: { inputPrice: 0.08, cachePrice: 0.01, outputPrice: 0.29, source: 'router-curated' }
    },
  },
  {
    id: 'llama-3-1-405b-instruct',
    name: 'Llama 3.1 405B Instruct',
    provider: 'meta',
    arenaRank: 4,
    inputPrice: 2.7,
    outputPrice: 2.7,
    cachePrice: 0.27,
    contextWindow: 128000,
    maxOutput: 8192,
    capabilities: ['function-calling', 'json-mode', 'code'],
    category: 'mid',
    releaseDate: '2024-07-23',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://llama.meta.com',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 2.7, cachePrice: 0.27, outputPrice: 2.7, source: 'aggregator-curated' },
      sumopod: { inputPrice: 2.8, cachePrice: 0.28, outputPrice: 2.8, source: 'router-curated' },
      deepinfra: { inputPrice: 2.85, cachePrice: 0.29, outputPrice: 2.85, source: 'router-curated' }
    },
  },
  {
    id: 'llama-guard-4',
    name: 'Llama Guard 4',
    provider: 'meta',
    arenaRank: 5,
    inputPrice: 0.05,
    outputPrice: 0.05,
    cachePrice: 0.005,
    contextWindow: 128000,
    maxOutput: 4096,
    capabilities: ['json-mode'],
    category: 'budget',
    releaseDate: '2025-04-05',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://llama.meta.com',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.05, cachePrice: 0.005, outputPrice: 0.05, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.055, cachePrice: 0.006, outputPrice: 0.06, source: 'router-curated' },
      deepinfra: { inputPrice: 0.06, cachePrice: 0.006, outputPrice: 0.06, source: 'router-curated' }
    },
  },

  // Cohere.
  {
    id: 'command-a-03-2025',
    name: 'Command A',
    provider: 'cohere',
    arenaRank: 1,
    inputPrice: 2.5,
    outputPrice: 10,
    cachePrice: 0.25,
    contextWindow: 256000,
    maxOutput: 8192,
    capabilities: ['function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2025-03-13',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.cohere.com/docs/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 2.5, cachePrice: 0.25, outputPrice: 10, source: 'aggregator-curated' },
      sumopod: { inputPrice: 2.6, cachePrice: 0.26, outputPrice: 10.4, source: 'router-curated' },
      deepinfra: { inputPrice: 2.65, cachePrice: 0.27, outputPrice: 10.5, source: 'router-curated' }
    },
  },
  {
    id: 'command-r-plus',
    name: 'Command R+',
    provider: 'cohere',
    arenaRank: 2,
    inputPrice: 2.5,
    outputPrice: 10,
    cachePrice: 0.25,
    contextWindow: 128000,
    maxOutput: 4096,
    capabilities: ['function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2024-04-04',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.cohere.com/docs/models',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 2.5, cachePrice: 0.25, outputPrice: 10, source: 'aggregator-curated' },
      sumopod: { inputPrice: 2.6, cachePrice: 0.26, outputPrice: 10.4, source: 'router-curated' },
      deepinfra: { inputPrice: 2.65, cachePrice: 0.27, outputPrice: 10.5, source: 'router-curated' }
    },
  },
  {
    id: 'command-r',
    name: 'Command R',
    provider: 'cohere',
    arenaRank: 3,
    inputPrice: 0.15,
    outputPrice: 0.6,
    cachePrice: 0.015,
    contextWindow: 128000,
    maxOutput: 4096,
    capabilities: ['function-calling', 'json-mode'],
    category: 'budget',
    releaseDate: '2024-03-11',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.cohere.com/docs/models',
    confidence: 'high',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.15, cachePrice: 0.015, outputPrice: 0.6, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.16, cachePrice: 0.016, outputPrice: 0.62, source: 'router-curated' },
      deepinfra: { inputPrice: 0.16, cachePrice: 0.016, outputPrice: 0.64, source: 'router-curated' }
    },
  },
  {
    id: 'command-r7b',
    name: 'Command R7B',
    provider: 'cohere',
    arenaRank: 4,
    inputPrice: 0.0375,
    outputPrice: 0.15,
    cachePrice: 0.004,
    contextWindow: 128000,
    maxOutput: 4096,
    capabilities: ['function-calling', 'json-mode'],
    category: 'budget',
    releaseDate: '2024-12-12',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.cohere.com/docs/models',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.0375, cachePrice: 0.004, outputPrice: 0.15, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.04, cachePrice: 0.004, outputPrice: 0.16, source: 'router-curated' },
      deepinfra: { inputPrice: 0.04, cachePrice: 0.004, outputPrice: 0.17, source: 'router-curated' }
    },
  },
  {
    id: 'command-light',
    name: 'Command Light',
    provider: 'cohere',
    arenaRank: 5,
    inputPrice: 0.3,
    outputPrice: 0.6,
    cachePrice: 0.03,
    contextWindow: 4096,
    maxOutput: 4096,
    capabilities: ['json-mode'],
    category: 'budget',
    releaseDate: '2023-08-01',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://docs.cohere.com/docs/models',
    confidence: 'low',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.3, cachePrice: 0.03, outputPrice: 0.6, source: 'aggregator-curated' }
    },
  },

  // MiniMax.
  {
    id: 'minimax-m2-7-highspeed',
    name: 'MiniMax M2.7 Highspeed',
    provider: 'minimax',
    arenaRank: 1,
    inputPrice: 0.6,
    outputPrice: 2.4,
    cachePrice: 0.12,
    contextWindow: 1000000,
    maxOutput: 80000,
    capabilities: ['reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://www.minimax.io/platform',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.6, cachePrice: 0.12, outputPrice: 2.4, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.62, cachePrice: 0.13, outputPrice: 2.5, source: 'router-curated' },
      deepinfra: { inputPrice: 0.25, cachePrice: 0.05, outputPrice: 1.0, source: 'deepinfra-api', deepinfraId: 'MiniMaxAI/MiniMax-M2.7' }
    },
  },
  {
    id: 'minimax-m2-7',
    name: 'MiniMax M2.7',
    provider: 'minimax',
    arenaRank: 2,
    inputPrice: 0.5,
    outputPrice: 2,
    cachePrice: 0.1,
    contextWindow: 1000000,
    maxOutput: 80000,
    capabilities: ['reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'flagship',
    releaseDate: '2026-06-24',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://www.minimax.io/platform',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.5, cachePrice: 0.1, outputPrice: 2, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.52, cachePrice: 0.11, outputPrice: 2.08, source: 'router-curated' },
      deepinfra: { inputPrice: 0.25, cachePrice: 0.05, outputPrice: 1.0, source: 'deepinfra-api', deepinfraId: 'MiniMaxAI/MiniMax-M2.7' }
    },
  },
  {
    id: 'minimax-m1',
    name: 'MiniMax M1',
    provider: 'minimax',
    arenaRank: 3,
    inputPrice: 0.4,
    outputPrice: 2.2,
    cachePrice: 0.1,
    contextWindow: 1000000,
    maxOutput: 80000,
    capabilities: ['reasoning', 'function-calling', 'json-mode', 'code'],
    category: 'reasoning',
    releaseDate: '2025-06-16',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://www.minimax.io/platform',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.4, cachePrice: 0.1, outputPrice: 2.2, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.42, cachePrice: 0.11, outputPrice: 2.3, source: 'router-curated' },
      deepinfra: { inputPrice: 0.44, cachePrice: 0.11, outputPrice: 2.35, source: 'router-curated' }
    },
  },
  {
    id: 'minimax-text-01',
    name: 'MiniMax Text-01',
    provider: 'minimax',
    arenaRank: 2,
    inputPrice: 0.2,
    outputPrice: 1.1,
    cachePrice: 0.05,
    contextWindow: 1000000,
    maxOutput: 8192,
    capabilities: ['function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2025-01-15',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://www.minimax.io/platform',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.2, cachePrice: 0.05, outputPrice: 1.1, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.22, cachePrice: 0.055, outputPrice: 1.15, source: 'router-curated' },
      deepinfra: { inputPrice: 0.22, cachePrice: 0.055, outputPrice: 1.18, source: 'router-curated' }
    },
  },
  {
    id: 'minimax-vl-01',
    name: 'MiniMax VL-01',
    provider: 'minimax',
    arenaRank: 3,
    inputPrice: 0.2,
    outputPrice: 1.1,
    cachePrice: 0.05,
    contextWindow: 1000000,
    maxOutput: 8192,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    category: 'mid',
    releaseDate: '2025-01-15',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://www.minimax.io/platform',
    confidence: 'medium',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.2, cachePrice: 0.05, outputPrice: 1.1, source: 'aggregator-curated' },
      sumopod: { inputPrice: 0.22, cachePrice: 0.055, outputPrice: 1.15, source: 'router-curated' },
      deepinfra: { inputPrice: 0.22, cachePrice: 0.055, outputPrice: 1.18, source: 'router-curated' }
    },
  },
  {
    id: 'abab6-5s-chat',
    name: 'abab6.5s Chat',
    provider: 'minimax',
    arenaRank: 4,
    inputPrice: 0.04,
    outputPrice: 0.16,
    cachePrice: 0.01,
    contextWindow: 245000,
    maxOutput: 8192,
    capabilities: ['json-mode'],
    category: 'budget',
    releaseDate: '2024-08-01',
    updatedAt: '2026-06-24',
    sourceUrl: 'https://www.minimax.io/platform',
    confidence: 'low',
    thirdPartyPricing: {
      openrouter: { inputPrice: 0.04, cachePrice: 0.01, outputPrice: 0.16, source: 'aggregator-curated' }
    },
  },
  {
    id: 'claude-opus-4-8',
    name: 'Claude Opus 4.8',
    provider: 'anthropic',
    arenaRank: 5,
    inputPrice: 15,
    outputPrice: 75,
    cachePrice: 1.5,
    contextWindow: 200000,
    category: 'flagship',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gemini-3-1-pro',
    name: 'Gemini 3.1 Pro',
    provider: 'google',
    arenaRank: 3,
    inputPrice: 2,
    outputPrice: 8,
    cachePrice: 0.5,
    contextWindow: 2000000,
    category: 'flagship',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gemini-3-1-flash',
    name: 'Gemini 3.1 Flash',
    provider: 'google',
    arenaRank: 10,
    inputPrice: 0.1,
    outputPrice: 0.4,
    cachePrice: 0.02,
    contextWindow: 1000000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gemini-3-1-flash-lite',
    name: 'Gemini 3.1 Flash-Lite',
    provider: 'google',
    arenaRank: 20,
    inputPrice: 0.05,
    outputPrice: 0.2,
    cachePrice: 0.01,
    contextWindow: 1000000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gemini-3-pro',
    name: 'Gemini 3 Pro',
    provider: 'google',
    arenaRank: 12,
    inputPrice: 1.5,
    outputPrice: 6,
    cachePrice: 0.3,
    contextWindow: 2000000,
    category: 'flagship',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gpt-5-5-pro',
    name: 'GPT-5.5 Pro',
    provider: 'openai',
    arenaRank: 1,
    inputPrice: 20,
    outputPrice: 80,
    cachePrice: 2,
    contextWindow: 200000,
    category: 'flagship',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gpt-5-4-pro',
    name: 'GPT-5.4 Pro',
    provider: 'openai',
    arenaRank: 4,
    inputPrice: 5,
    outputPrice: 20,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gpt-5-4-thinking',
    name: 'GPT-5.4 Thinking',
    provider: 'openai',
    arenaRank: 5,
    inputPrice: 4,
    outputPrice: 16,
    cachePrice: 0.4,
    contextWindow: 128000,
    category: 'reasoning',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gpt-5-3-instant',
    name: 'GPT-5.3 Instant',
    provider: 'openai',
    arenaRank: 15,
    inputPrice: 0.2,
    outputPrice: 0.8,
    cachePrice: 0.05,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'kimi-k2-7-code',
    name: 'Kimi K2.7 Code',
    provider: 'moonshot',
    arenaRank: 8,
    inputPrice: 0.8,
    outputPrice: 3.2,
    cachePrice: 0.1,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'deepseek-v4-pro-max',
    name: 'DeepSeek V4 Pro (Max)',
    provider: 'deepseek',
    arenaRank: 2,
    inputPrice: 1,
    outputPrice: 4,
    cachePrice: 0.1,
    contextWindow: 128000,
    category: 'flagship',
    releaseDate: '2026-06-28',
  },
  {
    id: 'deepseek-v4-pro-high',
    name: 'DeepSeek V4 Pro (High)',
    provider: 'deepseek',
    arenaRank: 3,
    inputPrice: 0.5,
    outputPrice: 2,
    cachePrice: 0.05,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash',
    provider: 'deepseek',
    arenaRank: 11,
    inputPrice: 0.05,
    outputPrice: 0.2,
    cachePrice: 0.01,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen-3-7-max',
    name: 'Qwen 3.7 Max',
    provider: 'alibaba',
    arenaRank: 6,
    inputPrice: 1.2,
    outputPrice: 6,
    cachePrice: 0.1,
    contextWindow: 128000,
    category: 'flagship',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen-3-5-397b-reasoning',
    name: 'Qwen 3.5 397B (Reasoning)',
    provider: 'alibaba',
    arenaRank: 7,
    inputPrice: 0.8,
    outputPrice: 3,
    cachePrice: 0.08,
    contextWindow: 128000,
    category: 'reasoning',
    releaseDate: '2026-06-28',
  },
  {
    id: 'glm-4-7-flash',
    name: 'GLM-4.7 Flash',
    provider: 'zhipu',
    arenaRank: 18,
    inputPrice: 0.02,
    outputPrice: 0.08,
    cachePrice: 0.005,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'claude-sonnet-4-8',
    name: 'Claude Sonnet 4.8',
    provider: 'anthropic',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'claude-sonnet-4-7',
    name: 'Claude Sonnet 4.7',
    provider: 'anthropic',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'claude-haiku-4',
    name: 'Claude Haiku 4',
    provider: 'anthropic',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gemini-3-1-ultra',
    name: 'Gemini 3.1 Ultra',
    provider: 'google',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gemini-3-1-flash-thinking',
    name: 'Gemini 3.1 Flash Thinking',
    provider: 'google',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gemini-3-flash-thinking',
    name: 'Gemini 3 Flash Thinking',
    provider: 'google',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gemma-3-27b',
    name: 'Gemma 3 27B',
    provider: 'google',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gemma-3-12b',
    name: 'Gemma 3 12B',
    provider: 'google',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gemma-3-4b',
    name: 'Gemma 3 4B',
    provider: 'google',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gpt-5-5-thinking',
    name: 'GPT-5.5 Thinking',
    provider: 'openai',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'reasoning',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gpt-5',
    name: 'GPT-5',
    provider: 'openai',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gpt-5-mini',
    name: 'GPT-5 Mini',
    provider: 'openai',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gpt-5-nano',
    name: 'GPT-5 Nano',
    provider: 'openai',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'o4',
    name: 'o4',
    provider: 'openai',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'reasoning',
    releaseDate: '2026-06-28',
  },
  {
    id: 'o4-mini',
    name: 'o4-mini',
    provider: 'openai',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'o3',
    name: 'o3',
    provider: 'openai',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'reasoning',
    releaseDate: '2026-06-28',
  },
  {
    id: 'o3-mini',
    name: 'o3-mini',
    provider: 'openai',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'gpt-image-1',
    name: 'GPT Image 1',
    provider: 'openai',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'kimi-2-5-pro',
    name: 'Kimi 2.5 Pro',
    provider: 'moonshot',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'flagship',
    releaseDate: '2026-06-28',
  },
  {
    id: 'kimi-2-5',
    name: 'Kimi 2.5',
    provider: 'moonshot',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'deepseek-v4-pro',
    name: 'DeepSeek V4 Pro',
    provider: 'deepseek',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'flagship',
    releaseDate: '2026-06-28',
  },
  {
    id: 'deepseek-r2',
    name: 'DeepSeek R2',
    provider: 'deepseek',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'reasoning',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen-3-6-max',
    name: 'Qwen 3.6 Max',
    provider: 'alibaba',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'flagship',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen-3-6-coder-next',
    name: 'Qwen 3.6 Coder Next',
    provider: 'alibaba',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen-3-6-235b',
    name: 'Qwen 3.6 235B',
    provider: 'alibaba',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen-3-6-32b',
    name: 'Qwen 3.6 32B',
    provider: 'alibaba',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen-3-6-14b',
    name: 'Qwen 3.6 14B',
    provider: 'alibaba',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen-3-6-8b',
    name: 'Qwen 3.6 8B',
    provider: 'alibaba',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen3-coder',
    name: 'Qwen3 Coder',
    provider: 'alibaba',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen3-vl',
    name: 'Qwen3 VL',
    provider: 'alibaba',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen3-omni',
    name: 'Qwen3 Omni',
    provider: 'alibaba',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'qwen3-math',
    name: 'Qwen3 Math',
    provider: 'alibaba',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'glm-5-1',
    name: 'GLM-5.1',
    provider: 'zhipu',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'glm-5',
    name: 'GLM-5',
    provider: 'zhipu',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'glm-4-7',
    name: 'GLM-4.7',
    provider: 'zhipu',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'glm-4-5-air',
    name: 'GLM-4.5 Air',
    provider: 'zhipu',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'glm-4-5-flash',
    name: 'GLM-4.5 Flash',
    provider: 'zhipu',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },
  {
    id: 'mimo-v2-5-pro',
    name: 'MiMo V2.5 Pro',
    provider: 'mimo',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'flagship',
    releaseDate: '2026-06-28',
  },
  {
    id: 'mimo-v2-5',
    name: 'MiMo V2.5',
    provider: 'mimo',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'mimo-v2',
    name: 'MiMo V2',
    provider: 'mimo',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'mid',
    releaseDate: '2026-06-28',
  },
  {
    id: 'mimo-7b-reasoner',
    name: 'MiMo 7B Reasoner',
    provider: 'mimo',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'reasoning',
    releaseDate: '2026-06-28',
  },
  {
    id: 'minimax-m2-5',
    name: 'MiniMax M2.5',
    provider: 'minimax',
    arenaRank: 10,
    inputPrice: 1,
    outputPrice: 2,
    cachePrice: 0.5,
    contextWindow: 128000,
    category: 'budget',
    releaseDate: '2026-06-28',
  },

];

const PROVIDER_SOURCE_URLS = {
  openai: 'https://platform.openai.com/docs/models',
  anthropic: 'https://docs.anthropic.com/en/docs/about-claude/models',
  google: 'https://ai.google.dev/gemini-api/docs/models',
  mistral: 'https://docs.mistral.ai/getting-started/models/',
  meta: 'https://llama.meta.com',
  deepseek: 'https://platform.deepseek.com/api-docs',
  cohere: 'https://docs.cohere.com/docs/models',
  alibaba: 'https://www.alibabacloud.com/en/solutions/generative-ai/qwen',
  moonshot: 'https://platform.moonshot.ai/docs',
  bytedance: 'https://www.volcengine.com/product/ark',
  zhipu: 'https://docs.z.ai',
  baidu: 'https://cloud.baidu.com',
  yi: 'https://www.01.ai',
  minimax: 'https://www.minimax.io/platform',
  stepfun: 'https://platform.stepfun.com',
  xiaomi: 'https://github.com/XiaomiMiMo/MiMo',
  xai: 'https://docs.x.ai/docs/models',
};

function getPricingSourceType(source) {
  if (!source) return 'curated';
  if (source.includes('official')) return 'official';
  if (source.includes('estimate') || source.includes('router-curated')) return 'estimate';
  return 'curated';
}

function inferOfficialPricingSource(model) {
  if (model.pricingSource) return model.pricingSource;
  if (model.confidence === 'high') return 'official-docs';
  if (model.confidence === 'low') return 'manual-estimate';
  return 'manual-curated';
}

function normalizePricing(pricing, fallbackSource = 'manual-curated', fallbackSourceUrl = '') {
  if (!pricing) return null;
  const source = pricing.source || fallbackSource;
  return {
    inputPrice: pricing.inputPrice ?? pricing.input ?? 0,
    cachePrice: pricing.cachePrice ?? pricing.cache ?? 0,
    outputPrice: pricing.outputPrice ?? pricing.output ?? 0,
    source,
    sourceType: pricing.sourceType || getPricingSourceType(source),
    sourceUrl: pricing.sourceUrl || fallbackSourceUrl,
    updatedAt: pricing.updatedAt || DEFAULT_DATA_UPDATED_AT,
  };
}

function calculateTopTierScore(model) {
  if (model.status === 'deprecated') return 0;

  const categoryScore = {
    flagship: 45,
    reasoning: 42,
    mid: 28,
    budget: 12,
  }[model.category] || 10;

  const capabilities = new Set(model.capabilities || []);
  let capabilityScore = 0;
  if (capabilities.has('reasoning')) capabilityScore += 18;
  if (capabilities.has('code')) capabilityScore += 12;
  if (capabilities.has('vision')) capabilityScore += 10;
  if (capabilities.has('function-calling')) capabilityScore += 8;
  if (capabilities.has('json-mode')) capabilityScore += 4;

  let contextScore = 0;
  if (model.contextWindow >= 1000000) contextScore = 15;
  else if (model.contextWindow >= 200000) contextScore = 10;
  else if (model.contextWindow >= 128000) contextScore = 7;
  else if (model.contextWindow >= 64000) contextScore = 4;

  const rankScore = model.arenaRank ? Math.max(0, 26 - (model.arenaRank * 4)) : 0;

  let recencyScore = 0;
  if (model.releaseDate) {
    const releasedAt = Date.parse(model.releaseDate);
    if (!Number.isNaN(releasedAt)) {
      const ageDays = Math.max(0, (Date.now() - releasedAt) / 86400000);
      if (ageDays <= 90) recencyScore = 12;
      else if (ageDays <= 180) recencyScore = 8;
      else if (ageDays <= 365) recencyScore = 4;
    }
  }

  return Math.round((categoryScore + capabilityScore + contextScore + rankScore + recencyScore) * 10) / 10;
}

function mergeCuratedModels(baseModels, curatedModels) {
  const byId = new Map(baseModels.map(model => [model.id, model]));

  curatedModels.forEach(model => {
    byId.set(model.id, {
      ...(byId.get(model.id) || {}),
      ...model,
    });
  });

  return Array.from(byId.values());
}

function normalizeModel(model) {
  const provider = PROVIDERS[model.provider];
  const sourceUrl = model.sourceUrl || PROVIDER_SOURCE_URLS[model.provider] || (provider && provider.website) || '';
  const pricingSource = inferOfficialPricingSource(model);
  const officialPricing = normalizePricing(model.officialPricing, pricingSource, sourceUrl) || normalizePricing({
    inputPrice: model.inputPrice ?? 0,
    cachePrice: model.cachePrice ?? 0,
    outputPrice: model.outputPrice ?? 0,
    source: pricingSource,
    sourceUrl,
    updatedAt: model.updatedAt || model.releaseDate || DEFAULT_DATA_UPDATED_AT,
  }, pricingSource, sourceUrl);

  model.inputPrice = officialPricing.inputPrice;
  model.cachePrice = officialPricing.cachePrice;
  model.outputPrice = officialPricing.outputPrice;
  model.officialPricing = officialPricing;

  if (model.thirdPartyPricing) {
    Object.keys(model.thirdPartyPricing).forEach(providerId => {
      const providerSourceUrl = providerId === 'openrouter'
        ? 'https://openrouter.ai/api/v1/models'
        : (PROVIDERS[providerId] && PROVIDERS[providerId].website) || '';
      const fallbackSource = providerId === 'openrouter' ? 'manual-curated' : 'manual-estimate';
      model.thirdPartyPricing[providerId] = normalizePricing(model.thirdPartyPricing[providerId], fallbackSource, providerSourceUrl);
    });
  }

  model.updatedAt = model.updatedAt || officialPricing.updatedAt || model.releaseDate || DEFAULT_DATA_UPDATED_AT;
  model.sourceUrl = sourceUrl;
  model.pricingSource = model.pricingSource || officialPricing.source || 'manual-curated';
  model.pricingSourceType = model.pricingSourceType || officialPricing.sourceType || getPricingSourceType(model.pricingSource);
  model.status = model.status || 'active';
  model.confidence = model.confidence || 'medium';
  model.benchmark = model.benchmark || {
    arenaRank: model.arenaRank || null,
    source: 'curated',
    updatedAt: model.updatedAt,
  };
  model.topTierScore = model.topTierScore ?? calculateTopTierScore(model);

  return model;
}

const MERGED_MODELS = mergeCuratedModels(MODELS, CURATED_TOP_MODELS);
MERGED_MODELS.forEach(model => {
  if (DEPRECATED_CURATED_MODEL_IDS.has(model.id)) {
    model.status = 'deprecated';
    model.confidence = 'low';
    model.pricingSource = 'manual-estimate';
  }
  normalizeModel(model);
});
MODELS.length = 0;
MODELS.push(...MERGED_MODELS);

// ============================================================
// FREE API MODELS — $0/token free tiers, plus a few near-zero-cost
// models (see priceUsdPerMillion per entry; 0 = truly free)
//
// Manually curated: only providers without a fetch script yet
// (Google AI Studio, Groq, Cerebras, Zhipu). OpenRouter's free
// tier rotates too often to hand-maintain — those entries are
// auto-generated from the existing OpenRouter fetch by
// scripts/build-openrouter-free-models.js and appended here at
// runtime via js/openrouter-free-models.generated.js.
//
// Groq entries verified against console.groq.com/docs/rate-limits
// on 2026-07-01 — re-check periodically, Groq has no public API
// for free-tier status so this can't be automated the same way.
// Updated: 2026-07-01
// ============================================================
const FREE_API_MODELS = [
  {
    id: 'free-gemini-2-5-flash',
    priceUsdPerMillion: 0,
    modelName: 'Gemini 2.5 Flash',
    modelId: 'gemini-2.5-flash',
    provider: 'google',
    apiEndpoint: 'generativelanguage.googleapis.com',
    contextWindow: 1048576,
    capabilities: ['vision', 'function-calling', 'json-mode', 'reasoning'],
    rateLimits: '15 RPM · 1M TPM · 250 RPD',
    requiresCard: false,
    signup: 'https://aistudio.google.com/apikey',
    docs: 'https://ai.google.dev/gemini-api/docs/models#gemini-2.5-flash',
    note_en: 'Google AI Studio free tier. 1M token context window.',
    note_id: 'Free tier Google AI Studio. Context window 1M token.',
  },
  {
    id: 'free-gemini-2-5-flash-lite',
    priceUsdPerMillion: 0,
    modelName: 'Gemini 2.5 Flash-Lite',
    modelId: 'gemini-2.5-flash-lite',
    provider: 'google',
    apiEndpoint: 'generativelanguage.googleapis.com',
    contextWindow: 1048576,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    rateLimits: '30 RPM · 1M TPM · 1000 RPD',
    requiresCard: false,
    signup: 'https://aistudio.google.com/apikey',
    docs: 'https://ai.google.dev/gemini-api/docs/models#gemini-2.5-flash-lite',
    note_en: 'Lightest free Gemini model. Higher rate limits than Flash.',
    note_id: 'Model Gemini gratis paling ringan. Rate limit lebih tinggi.',
  },
  {
    id: 'free-groq-llama4-scout',
    priceUsdPerMillion: 0,
    modelName: 'Llama 4 Scout 17B',
    modelId: 'meta-llama/llama-4-scout-17b-16e-instruct',
    provider: 'groq',
    apiEndpoint: 'api.groq.com/openai/v1',
    contextWindow: 131072,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    rateLimits: '30 RPM · 30K TPM · 1K RPD',
    requiresCard: false,
    signup: 'https://console.groq.com',
    docs: 'https://console.groq.com/docs/rate-limits',
    note_en: 'Ultra-fast LPU inference. OpenAI-compatible API.',
    note_id: 'Inferensi LPU ultra-cepat. API kompatibel OpenAI.',
  },
  {
    id: 'free-groq-llama33-70b',
    priceUsdPerMillion: 0,
    modelName: 'Llama 3.3 70B',
    modelId: 'llama-3.3-70b-versatile',
    provider: 'groq',
    apiEndpoint: 'api.groq.com/openai/v1',
    contextWindow: 128000,
    capabilities: ['function-calling', 'json-mode'],
    rateLimits: '30 RPM · 12K TPM · 1K RPD',
    requiresCard: false,
    signup: 'https://console.groq.com',
    docs: 'https://console.groq.com/docs/rate-limits',
    note_en: 'Strong general-purpose open model. Very fast on Groq.',
    note_id: 'Model open-source serba guna yang kuat. Sangat cepat.',
  },
  {
    id: 'free-glm-flash',
    priceUsdPerMillion: 0.01,
    modelName: 'GLM-4-Flash',
    modelId: 'glm-4-flash',
    provider: 'zhipu',
    apiEndpoint: 'open.bigmodel.cn/api/paas/v4',
    contextWindow: 128000,
    capabilities: ['vision', 'function-calling', 'json-mode'],
    rateLimits: 'Generous limits',
    requiresCard: false,
    signup: 'https://open.bigmodel.cn',
    docs: 'https://open.bigmodel.cn/dev/api/normal-model/glm-4',
    note_en: '$0.01/1M tokens — practically free for any workload.',
    note_id: '$0.01/1M token — praktis gratis untuk semua kebutuhan.',
  },
];

// ============================================================
// FREE CREDITS / STARTER OFFERS
// ============================================================
const PROMOS = [
  {
    id: 'promo-openai-credits',
    provider: 'openai',
    title_en: 'Free API Credits for New Users',
    title_id: 'Kredit API Gratis untuk Pengguna Baru',
    description_en: 'New users receive free API credits upon signing up. Great for testing GPT-4o and o-series models.',
    description_id: 'Pengguna baru mendapat kredit API gratis. Cocok untuk mencoba GPT-4o dan model seri-o.',
    type: 'free-credit',
    value: 'Free credits',
    isActive: true,
    link: 'https://platform.openai.com/signup',
  },
  {
    id: 'promo-anthropic-free',
    provider: 'anthropic',
    title_en: 'Free Tier on Claude.ai',
    title_id: 'Paket Gratis di Claude.ai',
    description_en: 'Use Claude for free on claude.ai with daily limits. API access requires a paid plan.',
    description_id: 'Gunakan Claude gratis di claude.ai. Akses API memerlukan paket berbayar.',
    type: 'free-tier',
    value: 'Free (web only)',
    isActive: true,
    link: 'https://claude.ai',
  },
  {
    id: 'promo-google-cloud',
    provider: 'google',
    title_en: 'Google Cloud Credits ($300)',
    title_id: 'Kredit Google Cloud ($300)',
    description_en: 'New Google Cloud users get $300 in free credits for Vertex AI and Gemini API paid tiers.',
    description_id: 'Pengguna baru Google Cloud mendapat kredit $300 untuk Vertex AI dan Gemini API.',
    type: 'free-credit',
    value: '$300',
    isActive: true,
    link: 'https://cloud.google.com/free',
  },
  {
    id: 'promo-deepseek-trial',
    provider: 'deepseek',
    title_en: 'Free Trial Credits',
    title_id: 'Kredit Uji Coba Gratis',
    description_en: 'New users receive free trial credits. DeepSeek V3 starts at just $0.27/1M tokens.',
    description_id: 'Pengguna baru mendapat kredit uji coba gratis. DeepSeek V3 mulai $0.27/1M token.',
    type: 'trial',
    value: 'Free credits',
    isActive: true,
    link: 'https://platform.deepseek.com',
  },
  {
    id: 'promo-moonshot-trial',
    provider: 'moonshot',
    title_en: 'Free Trial Credits for Kimi',
    title_id: 'Kredit Uji Coba Gratis untuk Kimi',
    description_en: 'New users get free trial credits for Kimi-K2 and other Moonshot AI models.',
    description_id: 'Pengguna baru mendapat kredit uji coba gratis untuk Kimi-K2 dan model Moonshot AI.',
    type: 'trial',
    value: 'Free credits',
    isActive: true,
    link: 'https://www.moonshot.cn',
  },
];

// ============================================================
// EXPOSE TO WINDOW (needed by generated pricing patches & app.js)
// ============================================================
if (typeof window !== 'undefined') {
  window.MODELS = MODELS;
  window.PROVIDERS = PROVIDERS;
  window.PROMOS = PROMOS;
  window.FREE_API_MODELS = FREE_API_MODELS;
  window.getProvider = id => PROVIDERS[id] || null;
  window.DEFAULT_DATA_UPDATED_AT = DEFAULT_DATA_UPDATED_AT;
}
